inferenceExtension:
  failureMode: "FailOpen"

inferencePool:
  targetPorts:
    - number: 8000
  modelServerType: vllm # vllm, sglang, triton-tensorrt-llm, trtllm-serve
  modelServerProtocol: http # http, grpc
  parser: "" # openai-parser, vllmgrpc-parser, passthrough-parser, or empty for auto-selection
  apiVersion: inference.networking.k8s.io/v1
  # modelServers: # REQUIRED
  #   matchLabels:
  #     app: vllm-qwen3-32b

# Options: ["gke", "istio", "none"]
provider:
  name: none

  # GKE-specific configuration.
  # This block is only used if name is "gke".
  gke:
    # Set to true if the cluster is an Autopilot cluster.
    autopilot: false

  # Istio-specific configuration.
  # This block is only used if name is "istio".
  istio:
    destinationRule:
      # Provide a way to override the default calculated host
      host: ""
      # Optional: Enables customization of the traffic policy
      trafficPolicy: {}
        # connectionPool:
        #   http:
        #     maxRequestsPerConnection: 256000

# experimentalHttpRoute section is used to deploy httproute as part of the epp helm chart.
# this section is temporary and should be extracted to a separate chart.
experimentalHttpRoute:
  enabled: false # a flag to indicate whether to create the httproute as part of the chart or not.
  inferenceGatewayName: inference-gateway
  inferenceGatewayNamespace: ""
  # HTTPRoute request timeout. Defaults to "300s". Unused when provider.name is gke.
  requestTimeout: "300s"
  # Example header matches:
  # headerMatches:
  #  x-my-custom-route-header: route-name


# Optional: Define InferenceObjective(s) for this InferencePool.
# Each InferenceObjective associates a name and priority with the InferencePool
# created in the chart release.
# Users reference these objectives by name in their request headers.
# This is only used for when InferenceObjectives are known ahead of time,
# they can still be created out of band of the chart release as needed.
inferenceObjectives: []
#   - name: high-priority
#     priority: 5
#   - name: low-priority
#     priority: 1
