apiVersion: v2
name: standalone
description: A Helm chart for Endpoint Picker

type: application

version: 0.0.0

appVersion: "0.0.0"

dependencies:
  - name: inference-extension
    version: 0.0.0
    repository: "file://../epplib"
    # This is needed to make use of the common values.yaml in ./config/charts/epplib/values.yaml
    alias: inferenceExtension
    import-values:
      - child: inferenceExtension
        parent: inferenceExtension
